### PR TITLE
enable command configuration in values yaml file

### PR DESCRIPTION
**Pull request by waakanni**
This first commit is to enable local testing by reviewers:

``` Bash
> helm template work-package

      - image: "ghga/work-package-service:2.0.3"
        command: ["sh", "-c"]
        args:
          - if [ -d "/vault/secrets" ]; then
              for f in /vault/secrets/*; do
                [ -f "$f" ] && . "$f";
              done
            fi;
            wps run-rest;
        name: release-name-rest


      - image: "ghga/work-package-service:2.0.3"
        command: ["sh", "-c"]
        args:
          - if [ -d "/vault/secrets" ]; then
              for f in /vault/secrets/*; do
                [ -f "$f" ] && . "$f";
              done
            fi;
            wps consume-events;
        name: release-name-consumer

> helm install wasiu-test work-package
> kubectl get deployment wasiu-test -o json

            "spec": {
                "containers": [
                    {
                        "args": [
                            "if [ -d \"/vault/secrets\" ]; then for f in /vault/secrets/*; do [ -f \"$f\" ] \u0026\u0026 . \"$f\"; done fi; wps run-rest;"
                        ],
                        "command": [
                            "sh",
                            "-c"
                        ],
                        "image": "ghga/work-package-service:2.0.3",


                        "args": [
                            "if [ -d \"/vault/secrets\" ]; then for f in /vault/secrets/*; do [ -f \"$f\" ] \u0026\u0026 . \"$f\"; done fi; wps consume-events;"
                        ],
                        "command": [
                            "sh",
                            "-c"
                        ],
                        "image": "ghga/work-package-service:2.0.3",

### CODE REVIEW

**Comment by dontseyit** [comment]
Are you going to update other services as well? @waakanni

**Comment by waakanni** [comment]
> Are you going to update other services as well? @waakanni

Yes, this is just to check if this solution works for your intended use case

**Comment by dontseyit** [comment]
Well, the solution seems straightforward to me. If it works for one I would expect the same for others. @waakanni 

I just wonder if we should name the commands as `command_primary, command_secondary` (even though I don't like them) or sth similar since we have some services that don't have this separation or have only one entry point like `data-portal-ui` or `notification`. We could use `command_rest` as default one but might be confusing if the service is not an API service. What you think? @ckaipf

**Comment by ckaipf** [comment]
Closed by #88

**Pull request closed without merging**
