### PR TITLE
Helper script to facilitate Chart updates when there is a new service release

### PR DESCRIPTION
**Pull request by ckaipf**
We could also consider to add a function which updates the versions and automatically adds the new or changed parameters (with the defaults from `config_schema.yaml`). Then we would have the complete update Charts workflow in one script.

- [ ] Add warning for secret placeholder

### CODE REVIEW

**Review by walzph — COMMENTED** [review]
Okay, this means our flow will work as follows:

1. Service Developer creates a new service release
2. DevOps Engineer (or action in service repo) trigger's a chart update
3. Chart Update runs this script
3.1. Script fetches latest release tags
3.2. Script checks for version diff -> updates chart.yaml if needed
3.3. Script checks for config diff -> updates values.yaml if needed
4. Changes are written to chart repo
5. Charts are "built" and deployed to helm repo (hosted on gh-pages branch).

Correct me if I got something wrong.

And question: Can we safely assume that there will never be a config diff without a version diff?

**Comment by ckaipf** [comment]
Yes, that's how the workflow should look like. 

 5. Since there are some uncertainties I would leave that as a manual step. The person who runs the script should do a sanity 
     check on the changes.

"And question: Can we safely assume that there will never be a config diff without a version diff?"
In my opinion we can safely assume that. The service releases should be immutable.

**Comment by dontseyit** [comment]
As I can see until now, the developments, unless they are small bug fixes or template updates in services, are most of the time interdependent to function harmoniously. We may need to wait until a group of services are released so not every release will be deployed immediately. The test-bed is the best suitable way to test new service releases and catch problems before deployment. There is still an ongoing discussion about when we can say these services are ready to deploy and when to decide to deploy a pack of services. This is a kind of service integration responsibility that requires manual overview when there is a new release.

**Comment by ckaipf** [comment]
> As I can see until now, the developments, unless they are small bug fixes or template updates in services, are most of the time interdependent to function harmoniously. We may need to wait until a group of services are released so not every release will be deployed because there is no guarantee that they are going to work together. The test-bed is the best suitable way to test new service releases and catch problems before deployment. There is still an ongoing discussion about how we can say these services are ready to deploy and when to decide to deploy a pack of services. This is a kind of service integration responsibility that requires manual overview when there is a new release.

True, at the moment we have two ways to run integration tests on multiple services together. Either we publish them as Charts (e.g. Chart version 0.2.1-alpha) or we set the image tags in helmfile.

**Pull request closed without merging**
